// Turns src/ into dist/. No dependencies: tokens.json is the same file the
// design system page on claude.ai edits, so a change there is copied here
// and rebuilt, never retyped.
//
//   node scripts/build.mjs          write dist/
//   node scripts/build.mjs --check  fail if dist/ is out of date
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const P = '--mt-' // every variable is prefixed so it cannot collide with a project's own
const tokens = JSON.parse(readFileSync('src/tokens.json', 'utf8'))
const v = (name) => `${P}${name}`

const colorValue = (value) => {
  const m = /^\{(.+)\}$/.exec(value)
  return m ? `var(${v(m[1])})` : value
}

function tokensCss() {
  const themes = tokens.color.themes.map((t) => t.id)
  const [first, ...rest] = themes
  const pick = (t, theme) => (typeof t.value === 'string' ? (theme === first ? t.value : undefined) : t.value[theme])
  const out = [`/* Generated from src/tokens.json by scripts/build.mjs. Do not edit. */`]

  const rootLines = []
  for (const t of tokens.color.tokens) rootLines.push(`  ${v(t.name)}: ${colorValue(pick(t, first))};`)
  for (const t of tokens.shadow?.tokens ?? []) rootLines.push(`  ${v(t.name)}: ${typeof t.value === 'string' ? t.value : t.value[first]};`)
  out.push(`:root, [data-theme="${first}"] {\n${rootLines.join('\n')}\n}`)

  for (const theme of rest) {
    const lines = []
    for (const t of tokens.color.tokens) {
      const val = pick(t, theme)
      if (val !== undefined) lines.push(`  ${v(t.name)}: ${colorValue(val)};`)
    }
    if (lines.length) out.push(`[data-theme="${theme}"] {\n${lines.join('\n')}\n}`)
  }

  const scale = []
  for (const [key, fam] of Object.entries(tokens)) {
    if (['name', 'version', 'meta', 'color', 'type', 'shadow'].includes(key) || !fam?.tokens) continue
    for (const t of fam.tokens) scale.push(`  ${v(t.name)}: ${t.value};`)
  }
  for (const [key, stack] of Object.entries(tokens.type.families)) scale.push(`  ${v('font-' + key)}: ${stack};`)
  out.push(`:root {\n${scale.join('\n')}\n}`)

  for (const group of tokens.type.groups) {
    for (const s of group.styles) {
      const decl = [`font-family: var(${v('font-' + (s.family ?? group.family))})`, `font-size: ${s.fontSize}`]
      if (s.lineHeight !== undefined) decl.push(`line-height: ${s.lineHeight}`)
      if (s.fontWeight !== undefined) decl.push(`font-weight: ${s.fontWeight}`)
      if (s.letterSpacing !== undefined) decl.push(`letter-spacing: ${s.letterSpacing}`)
      out.push(`.mt-t-${s.name} { ${decl.join('; ')}; }`)
    }
  }
  return out.join('\n\n') + '\n'
}

function componentsCss() {
  const src = readFileSync('src/components.css', 'utf8')
  return `/* Generated from src/components.css by scripts/build.mjs. Do not edit. */\n\n` + src.replaceAll('var(--', `var(${P}`)
}

// Every family the tokens name, from Google Fonts, at the weights the system uses.
function fontsCss() {
  const weights = {
    'JetBrains Mono': '400;500;700',
    'Inter Tight': '400;500',
    'EB Garamond': '400;500;600',
    Inter: '400;500;600',
    'IBM Plex Mono': '400;500',
  }
  const named = Object.values(tokens.type.families).map((s) => s.split(',')[0].replace(/"/g, '').trim())
  const q = named
    .filter((f) => weights[f])
    .map((f) => `family=${f.replaceAll(' ', '+')}:wght@${weights[f]}`)
    .join('&')
  return `/* Generated by scripts/build.mjs. Do not edit. */\n@import url('https://fonts.googleapis.com/css2?${q}&display=swap');\n`
}

const files = {
  'dist/tokens.css': tokensCss(),
  'dist/components.css': componentsCss(),
  'dist/fonts.css': fontsCss(),
  'dist/index.css': `/* Generated by scripts/build.mjs. Do not edit. */\n@import './fonts.css';\n@import './tokens.css';\n@import './components.css';\n`,
}

if (process.argv.includes('--check')) {
  const stale = Object.entries(files).filter(([path, body]) => {
    try { return readFileSync(path, 'utf8') !== body } catch { return true }
  })
  if (stale.length) {
    console.error(`dist/ is out of date: ${stale.map(([p]) => p).join(', ')}. Run npm run build.`)
    process.exit(1)
  }
  console.log('dist/ is up to date.')
} else {
  mkdirSync('dist', { recursive: true })
  for (const [path, body] of Object.entries(files)) writeFileSync(path, body)
  console.log(`Wrote ${Object.keys(files).join(', ')}.`)
}
